name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # This action checks out your repository
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'  # Use whatever node version your project requires

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn run build
        
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages2 # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
